# Generated by Django 2.0 on 2019-06-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('files', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instname', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('feedback', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('message', models.TextField(max_length=10000)),
            ],
        ),
    ]
